defaults:
  - train_schema
  - profile: auto
  - model: dummy
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
