defaults:
  - train_schema
  - profile: auto
  - model: dummy
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

logging:
  mlflow:
    tracking_uri: ${oc.env:MLFLOW_TRACKING_URI,null}

run:
  root: ${oc.env:REVERSI_ZERO_RUN_ROOT,runs}

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
