"""
Training data loading utilities for AlphaZero self-play data.
"""

from bisect import bisect_right
from itertools import accumulate
from pathlib import Path
from typing import Literal

import numpy as np
import torch
from torch.utils.data import Dataset

SymmetryCount = Literal[1, 2, 4, 8]
_SYMMETRY_INDICES: dict[int, tuple[int, ...]] = {
    1: (0,),
    2: (0, 4),
    4: (0, 1, 2, 3),
    8: (0, 1, 2, 3, 4, 5, 6, 7),
}


class SelfPlayDataset(Dataset):
    """
    Dataset for loading self-play training data generated by Rust backend.

    Expected file structure in data_dir:
    - states.npy: (N, 3, 8, 8) float32 board states
    - policies.npy: (N, 64) float32 MCTS visit distributions
    - values.npy: (N,) float32 game outcomes from perspective of current player

    Args:
        data_dir: Directory containing states.npy, policies.npy, values.npy
    """

    def __init__(self, data_dir: Path | str):
        self.data_dir = Path(data_dir)

        # Load all data into memory (self-play datasets are typically small enough)
        states_path = self.data_dir / "states.npy"
        policies_path = self.data_dir / "policies.npy"
        values_path = self.data_dir / "values.npy"

        if not states_path.exists():
            raise FileNotFoundError(f"States file not found: {states_path}")
        if not policies_path.exists():
            raise FileNotFoundError(f"Policies file not found: {policies_path}")
        if not values_path.exists():
            raise FileNotFoundError(f"Values file not found: {values_path}")

        self.states = np.load(states_path)
        self.policies = np.load(policies_path)
        self.values = np.load(values_path)

        # Validate shapes
        n_samples = len(self.states)
        if len(self.policies) != n_samples:
            raise ValueError(
                f"Mismatch: states has {n_samples} samples, "
                f"but policies has {len(self.policies)}"
            )
        if len(self.values) != n_samples:
            raise ValueError(
                f"Mismatch: states has {n_samples} samples, "
                f"but values has {len(self.values)}"
            )

        # Validate data types and shapes
        if self.states.shape[1:] != (3, 8, 8):
            raise ValueError(
                f"Expected states shape (N, 3, 8, 8), got {self.states.shape}"
            )
        if self.policies.shape[1:] != (64,):
            raise ValueError(
                f"Expected policies shape (N, 64), got {self.policies.shape}"
            )
        if self.values.ndim != 1:
            raise ValueError(f"Expected values shape (N,), got {self.values.shape}")

    def __len__(self) -> int:
        return len(self.states)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Returns:
            state: (3, 8, 8) tensor
            policy: (64,) tensor (probability distribution)
            value: scalar tensor (outcome from current player's perspective)
        """
        state = torch.from_numpy(self.states[idx]).float()
        policy = torch.from_numpy(self.policies[idx]).float()
        value = torch.tensor(self.values[idx], dtype=torch.float32)

        return state, policy, value

    def get_stats(self) -> dict[str, float]:
        """Get dataset statistics for logging."""
        return {
            "num_samples": len(self),
            "mean_value": float(self.values.mean()),
            "std_value": float(self.values.std()),
            "positive_values": float((self.values > 0).sum()),
            "negative_values": float((self.values < 0).sum()),
            "zero_values": float((self.values == 0).sum()),
        }


class ReplayBufferDataset(Dataset):
    """Lazily concatenate self-play datasets from multiple iterations."""

    def __init__(self, data_dirs: list[Path | str]) -> None:
        if not data_dirs:
            raise ValueError("Replay buffer requires at least one data directory")
        self.datasets = [SelfPlayDataset(data_dir) for data_dir in data_dirs]
        if any(len(dataset) == 0 for dataset in self.datasets):
            raise ValueError("Replay buffer datasets must not be empty")
        self.cumulative_sizes = list(
            accumulate(len(dataset) for dataset in self.datasets)
        )

    def __len__(self) -> int:
        return self.cumulative_sizes[-1]

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        if idx < 0:
            idx += len(self)
        if idx < 0 or idx >= len(self):
            raise IndexError(idx)

        dataset_idx = bisect_right(self.cumulative_sizes, idx)
        previous_size = self.cumulative_sizes[dataset_idx - 1] if dataset_idx else 0
        return self.datasets[dataset_idx][idx - previous_size]

    def get_stats(self) -> dict[str, float]:
        """Aggregate statistics without concatenating the underlying arrays."""
        num_samples = len(self)
        value_sum = sum(
            float(dataset.values.sum(dtype=np.float64)) for dataset in self.datasets
        )
        value_squared_sum = sum(
            float(np.square(dataset.values, dtype=np.float64).sum())
            for dataset in self.datasets
        )
        mean_value = value_sum / num_samples
        variance = max(0.0, value_squared_sum / num_samples - mean_value**2)
        return {
            "num_samples": float(num_samples),
            "mean_value": mean_value,
            "std_value": variance**0.5,
            "positive_values": sum(
                float((dataset.values > 0).sum()) for dataset in self.datasets
            ),
            "negative_values": sum(
                float((dataset.values < 0).sum()) for dataset in self.datasets
            ),
            "zero_values": sum(
                float((dataset.values == 0).sum()) for dataset in self.datasets
            ),
        }


class SymmetryAugmentedDataset(Dataset):
    """Lazily expose D4 rotations/reflections of self-play examples."""

    def __init__(
        self,
        dataset: SelfPlayDataset | ReplayBufferDataset,
        symmetry_count: SymmetryCount = 8,
    ) -> None:
        if symmetry_count not in _SYMMETRY_INDICES:
            raise ValueError("symmetry_count must be one of 1, 2, 4, or 8")
        self.dataset = dataset
        self.symmetry_count = symmetry_count
        self.symmetry_indices = _SYMMETRY_INDICES[symmetry_count]

    def __len__(self) -> int:
        return len(self.dataset) * self.symmetry_count

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        if idx < 0:
            idx += len(self)
        if idx < 0 or idx >= len(self):
            raise IndexError(idx)

        source_idx, symmetry_slot = divmod(idx, self.symmetry_count)
        symmetry_idx = self.symmetry_indices[symmetry_slot]
        state, policy, value = self.dataset[source_idx]
        policy_board = policy.view(8, 8)

        rotation = symmetry_idx % 4
        if symmetry_idx >= 4:
            state = torch.flip(state, dims=(-1,))
            policy_board = torch.flip(policy_board, dims=(-1,))
        if rotation:
            state = torch.rot90(state, rotation, dims=(-2, -1))
            policy_board = torch.rot90(policy_board, rotation, dims=(-2, -1))

        return state.contiguous(), policy_board.reshape(64).contiguous(), value

    def get_stats(self) -> dict[str, float]:
        stats = self.dataset.get_stats()
        stats["num_samples"] = float(len(self))
        for key in ("positive_values", "negative_values", "zero_values"):
            stats[key] *= self.symmetry_count
        return stats
